// Regenerates `src/registry.ts` and the `@std/*` entries of `deno.json`
// from the JSR metadata for the Deno standard library.
//
// The registry is the interpreter's allow list: a CAD script may import
// exactly the specifiers it names, and nothing else.  Every entry is also a
// statically analysable dynamic import, which is what makes `deno compile`
// embed the module in the binary.  Embedding matters because the sandboxed
// worker runs without import permission and so cannot fetch anything at
// run time.
//
// Usage: deno run -A scripts/gen-registry.ts

const JSR = "https://jsr.io"

// The complete @std scope, as of the last run of this script.
const STD_PACKAGES = [
    "assert",
    "async",
    "bytes",
    "cache",
    "cbor",
    "cli",
    "collections",
    "crypto",
    "csv",
    "data-structures",
    "datetime",
    "dotenv",
    "encoding",
    "expect",
    "fmt",
    "front-matter",
    "fs",
    "html",
    "http",
    "ini",
    "internal",
    "io",
    "json",
    "jsonc",
    "log",
    "math",
    "media-types",
    "msgpack",
    "net",
    "path",
    "random",
    "regexp",
    "semver",
    "streams",
    "tar",
    "testing",
    "text",
    "toml",
    "ulid",
    "uuid",
    "webgpu",
    "xml",
    "yaml",
]

// Packages deliberately left out of the interpreter.
const EXCLUDED: Record<string, string> = {
    http: "network access",
    net: "network access",
    // Not a public standard library; it is an implementation detail of the
    // other @std packages, which vendor it transitively anyway.
    internal: "not a public standard library",
    // Requires --unstable-webgpu and a GPU adapter, neither of which the
    // interpreter's sandbox provides.
    webgpu: "requires unstable GPU access",
}

interface PackageInfo {
    name: string
    version: string
    exports: string[]
}

async function fetchJson(url: string): Promise<Record<string, unknown>> {
    const response = await fetch(url, {
        headers: { "user-agent": "cadscript-gen-registry" },
    })
    if (!response.ok) {
        throw new Error(`${url}: ${response.status} ${response.statusText}`)
    }
    return await response.json()
}

async function packageInfo(name: string): Promise<PackageInfo> {
    const meta = await fetchJson(`${JSR}/@std/${name}/meta.json`)
    const version = meta.latest as string
    const versionMeta = await fetchJson(
        `${JSR}/@std/${name}/${version}_meta.json`,
    )
    const exports = Object.keys(
        (versionMeta.exports ?? {}) as Record<string, string>,
    )
    return { name, version, exports: exports.sort() }
}

// Turns an export key from the JSR metadata ("." or "./join") into the
// specifier a script would write ("@std/path" or "@std/path/join").
function specifier(pkg: string, exportKey: string): string {
    const suffix = exportKey === "." ? "" : exportKey.replace(/^\./, "")
    return `@std/${pkg}${suffix}`
}

function renderRegistry(packages: PackageInfo[]): string {
    const lines: string[] = [
        "// @generated by scripts/gen-registry.ts -- do not edit by hand.",
        "//",
        "// The modules a CAD script is allowed to import.  Each value is a",
        "// literal dynamic import so that `deno compile` embeds the module",
        "// in the binary; the sandboxed worker has no import permission and",
        "// so can only load what was embedded ahead of time.",
        "",
        "export type ModuleLoader = () => Promise<unknown>",
        "",
        "export const MODULES: Readonly<Record<string, ModuleLoader>> = {",
    ]
    const entries: [string, string][] = []
    for (const pkg of packages) {
        for (const exportKey of pkg.exports) {
            const name = specifier(pkg.name, exportKey)
            entries.push([name, name])
        }
    }
    // Optique, which every script must import, and replicad, which is the
    // point of the exercise.
    for (
        const name of [
            "@optique/core",
            "@optique/core/annotations",
            "@optique/core/completion",
            "@optique/core/constructs",
            "@optique/core/dependency",
            "@optique/core/doc",
            "@optique/core/facade",
            "@optique/core/fluent",
            "@optique/core/message",
            "@optique/core/modifiers",
            "@optique/core/nonempty",
            "@optique/core/parser",
            "@optique/core/primitives",
            "@optique/core/program",
            "@optique/core/suggestion",
            "@optique/core/usage",
            "@optique/core/valueparser",
            "@optique/temporal",
            "replicad",
        ]
    ) {
        entries.push([name, name])
    }
    entries.sort(([a], [b]) => a < b ? -1 : a > b ? 1 : 0)
    for (const [name, target] of entries) {
        lines.push(`    ${JSON.stringify(name)}: () => import(`)
        lines.push(`        ${JSON.stringify(target)}`)
        lines.push(`    ),`)
    }
    lines.push("}")
    lines.push("")
    lines.push("/** Every specifier a CAD script may import. */")
    lines.push(
        "export const ALLOWED: readonly string[] = Object.keys(MODULES)",
    )
    lines.push("")
    return lines.join("\n")
}

async function main() {
    const included = STD_PACKAGES.filter((p) => !(p in EXCLUDED))
    console.error(
        `fetching metadata for ${included.length} @std packages ` +
            `(${Object.keys(EXCLUDED).length} excluded)`,
    )
    const packages = await Promise.all(included.map(packageInfo))

    const registry = renderRegistry(packages)
    await Deno.writeTextFile("src/registry.ts", registry)
    console.error(`wrote src/registry.ts`)

    // Rewrite the @std/* half of the import map, leaving everything else
    // (replicad, Optique) as it is.
    const config = JSON.parse(await Deno.readTextFile("deno.json"))
    const imports: Record<string, string> = {}
    for (const pkg of packages) {
        imports[`@std/${pkg.name}`] = `jsr:@std/${pkg.name}@^${pkg.version}`
    }
    for (const [key, value] of Object.entries(config.imports ?? {})) {
        if (!key.startsWith("@std/")) imports[key] = value as string
    }
    config.imports = Object.fromEntries(
        Object.entries(imports).sort(([a], [b]) => a < b ? -1 : 1),
    )
    await Deno.writeTextFile(
        "deno.json",
        JSON.stringify(config, null, 4) + "\n",
    )
    console.error("updated deno.json imports")

    const count = packages.reduce((n, p) => n + p.exports.length, 0)
    console.error(`${count} @std modules allowed`)
}

if (import.meta.main) await main()
