// @generated by scripts/gen-registry.ts -- do not edit by hand.
//
// The modules a CAD script is allowed to import.  Each value is a
// literal dynamic import so that `deno compile` embeds the module
// in the binary; the sandboxed worker has no import permission and
// so can only load what was embedded ahead of time.

export type ModuleLoader = () => Promise<unknown>

export const MODULES: Readonly<Record<string, ModuleLoader>> = {
    "@optique/core": () =>
        import(
            "@optique/core"
        ),
    "@optique/core/annotations": () =>
        import(
            "@optique/core/annotations"
        ),
    "@optique/core/completion": () =>
        import(
            "@optique/core/completion"
        ),
    "@optique/core/constructs": () =>
        import(
            "@optique/core/constructs"
        ),
    "@optique/core/dependency": () =>
        import(
            "@optique/core/dependency"
        ),
    "@optique/core/doc": () =>
        import(
            "@optique/core/doc"
        ),
    "@optique/core/facade": () =>
        import(
            "@optique/core/facade"
        ),
    "@optique/core/fluent": () =>
        import(
            "@optique/core/fluent"
        ),
    "@optique/core/message": () =>
        import(
            "@optique/core/message"
        ),
    "@optique/core/modifiers": () =>
        import(
            "@optique/core/modifiers"
        ),
    "@optique/core/nonempty": () =>
        import(
            "@optique/core/nonempty"
        ),
    "@optique/core/parser": () =>
        import(
            "@optique/core/parser"
        ),
    "@optique/core/primitives": () =>
        import(
            "@optique/core/primitives"
        ),
    "@optique/core/program": () =>
        import(
            "@optique/core/program"
        ),
    "@optique/core/suggestion": () =>
        import(
            "@optique/core/suggestion"
        ),
    "@optique/core/usage": () =>
        import(
            "@optique/core/usage"
        ),
    "@optique/core/valueparser": () =>
        import(
            "@optique/core/valueparser"
        ),
    "@optique/temporal": () =>
        import(
            "@optique/temporal"
        ),
    "@std/assert": () =>
        import(
            "@std/assert"
        ),
    "@std/assert/almost-equals": () =>
        import(
            "@std/assert/almost-equals"
        ),
    "@std/assert/array-includes": () =>
        import(
            "@std/assert/array-includes"
        ),
    "@std/assert/assert": () =>
        import(
            "@std/assert/assert"
        ),
    "@std/assert/assertion-error": () =>
        import(
            "@std/assert/assertion-error"
        ),
    "@std/assert/equal": () =>
        import(
            "@std/assert/equal"
        ),
    "@std/assert/equals": () =>
        import(
            "@std/assert/equals"
        ),
    "@std/assert/exists": () =>
        import(
            "@std/assert/exists"
        ),
    "@std/assert/fail": () =>
        import(
            "@std/assert/fail"
        ),
    "@std/assert/false": () =>
        import(
            "@std/assert/false"
        ),
    "@std/assert/greater": () =>
        import(
            "@std/assert/greater"
        ),
    "@std/assert/greater-or-equal": () =>
        import(
            "@std/assert/greater-or-equal"
        ),
    "@std/assert/instance-of": () =>
        import(
            "@std/assert/instance-of"
        ),
    "@std/assert/is-error": () =>
        import(
            "@std/assert/is-error"
        ),
    "@std/assert/less": () =>
        import(
            "@std/assert/less"
        ),
    "@std/assert/less-or-equal": () =>
        import(
            "@std/assert/less-or-equal"
        ),
    "@std/assert/match": () =>
        import(
            "@std/assert/match"
        ),
    "@std/assert/not-equals": () =>
        import(
            "@std/assert/not-equals"
        ),
    "@std/assert/not-instance-of": () =>
        import(
            "@std/assert/not-instance-of"
        ),
    "@std/assert/not-match": () =>
        import(
            "@std/assert/not-match"
        ),
    "@std/assert/not-strict-equals": () =>
        import(
            "@std/assert/not-strict-equals"
        ),
    "@std/assert/object-match": () =>
        import(
            "@std/assert/object-match"
        ),
    "@std/assert/rejects": () =>
        import(
            "@std/assert/rejects"
        ),
    "@std/assert/strict-equals": () =>
        import(
            "@std/assert/strict-equals"
        ),
    "@std/assert/string-includes": () =>
        import(
            "@std/assert/string-includes"
        ),
    "@std/assert/throws": () =>
        import(
            "@std/assert/throws"
        ),
    "@std/assert/unimplemented": () =>
        import(
            "@std/assert/unimplemented"
        ),
    "@std/assert/unreachable": () =>
        import(
            "@std/assert/unreachable"
        ),
    "@std/assert/unstable-equals": () =>
        import(
            "@std/assert/unstable-equals"
        ),
    "@std/assert/unstable-never": () =>
        import(
            "@std/assert/unstable-never"
        ),
    "@std/assert/unstable-strict-equals": () =>
        import(
            "@std/assert/unstable-strict-equals"
        ),
    "@std/async": () =>
        import(
            "@std/async"
        ),
    "@std/async/abortable": () =>
        import(
            "@std/async/abortable"
        ),
    "@std/async/all-keyed": () =>
        import(
            "@std/async/all-keyed"
        ),
    "@std/async/channel": () =>
        import(
            "@std/async/channel"
        ),
    "@std/async/deadline": () =>
        import(
            "@std/async/deadline"
        ),
    "@std/async/debounce": () =>
        import(
            "@std/async/debounce"
        ),
    "@std/async/delay": () =>
        import(
            "@std/async/delay"
        ),
    "@std/async/lazy": () =>
        import(
            "@std/async/lazy"
        ),
    "@std/async/mux-async-iterator": () =>
        import(
            "@std/async/mux-async-iterator"
        ),
    "@std/async/poll": () =>
        import(
            "@std/async/poll"
        ),
    "@std/async/pool": () =>
        import(
            "@std/async/pool"
        ),
    "@std/async/retry": () =>
        import(
            "@std/async/retry"
        ),
    "@std/async/tee": () =>
        import(
            "@std/async/tee"
        ),
    "@std/async/unstable-abortable": () =>
        import(
            "@std/async/unstable-abortable"
        ),
    "@std/async/unstable-circuit-breaker": () =>
        import(
            "@std/async/unstable-circuit-breaker"
        ),
    "@std/async/unstable-mux-async-iterator": () =>
        import(
            "@std/async/unstable-mux-async-iterator"
        ),
    "@std/async/unstable-pool-settled": () =>
        import(
            "@std/async/unstable-pool-settled"
        ),
    "@std/async/unstable-semaphore": () =>
        import(
            "@std/async/unstable-semaphore"
        ),
    "@std/async/unstable-throttle": () =>
        import(
            "@std/async/unstable-throttle"
        ),
    "@std/async/unstable-wait-for": () =>
        import(
            "@std/async/unstable-wait-for"
        ),
    "@std/bytes": () =>
        import(
            "@std/bytes"
        ),
    "@std/bytes/concat": () =>
        import(
            "@std/bytes/concat"
        ),
    "@std/bytes/copy": () =>
        import(
            "@std/bytes/copy"
        ),
    "@std/bytes/ends-with": () =>
        import(
            "@std/bytes/ends-with"
        ),
    "@std/bytes/equals": () =>
        import(
            "@std/bytes/equals"
        ),
    "@std/bytes/includes-needle": () =>
        import(
            "@std/bytes/includes-needle"
        ),
    "@std/bytes/index-of-needle": () =>
        import(
            "@std/bytes/index-of-needle"
        ),
    "@std/bytes/last-index-of-needle": () =>
        import(
            "@std/bytes/last-index-of-needle"
        ),
    "@std/bytes/repeat": () =>
        import(
            "@std/bytes/repeat"
        ),
    "@std/bytes/starts-with": () =>
        import(
            "@std/bytes/starts-with"
        ),
    "@std/cache": () =>
        import(
            "@std/cache"
        ),
    "@std/cache/lru-cache": () =>
        import(
            "@std/cache/lru-cache"
        ),
    "@std/cache/memoize": () =>
        import(
            "@std/cache/memoize"
        ),
    "@std/cache/ttl-cache": () =>
        import(
            "@std/cache/ttl-cache"
        ),
    "@std/cbor": () =>
        import(
            "@std/cbor"
        ),
    "@std/cbor/array-encoder-stream": () =>
        import(
            "@std/cbor/array-encoder-stream"
        ),
    "@std/cbor/byte-encoder-stream": () =>
        import(
            "@std/cbor/byte-encoder-stream"
        ),
    "@std/cbor/decode-cbor": () =>
        import(
            "@std/cbor/decode-cbor"
        ),
    "@std/cbor/decode-cbor-sequence": () =>
        import(
            "@std/cbor/decode-cbor-sequence"
        ),
    "@std/cbor/encode-cbor": () =>
        import(
            "@std/cbor/encode-cbor"
        ),
    "@std/cbor/encode-cbor-sequence": () =>
        import(
            "@std/cbor/encode-cbor-sequence"
        ),
    "@std/cbor/map-encoder-stream": () =>
        import(
            "@std/cbor/map-encoder-stream"
        ),
    "@std/cbor/sequence-decoder-stream": () =>
        import(
            "@std/cbor/sequence-decoder-stream"
        ),
    "@std/cbor/sequence-encoder-stream": () =>
        import(
            "@std/cbor/sequence-encoder-stream"
        ),
    "@std/cbor/tag": () =>
        import(
            "@std/cbor/tag"
        ),
    "@std/cbor/text-encoder-stream": () =>
        import(
            "@std/cbor/text-encoder-stream"
        ),
    "@std/cbor/types": () =>
        import(
            "@std/cbor/types"
        ),
    "@std/cli": () =>
        import(
            "@std/cli"
        ),
    "@std/cli/parse-args": () =>
        import(
            "@std/cli/parse-args"
        ),
    "@std/cli/prompt-secret": () =>
        import(
            "@std/cli/prompt-secret"
        ),
    "@std/cli/unicode-width": () =>
        import(
            "@std/cli/unicode-width"
        ),
    "@std/cli/unstable-ansi": () =>
        import(
            "@std/cli/unstable-ansi"
        ),
    "@std/cli/unstable-get-cursor": () =>
        import(
            "@std/cli/unstable-get-cursor"
        ),
    "@std/cli/unstable-progress-bar": () =>
        import(
            "@std/cli/unstable-progress-bar"
        ),
    "@std/cli/unstable-progress-bar-stream": () =>
        import(
            "@std/cli/unstable-progress-bar-stream"
        ),
    "@std/cli/unstable-prompt-multiple-select": () =>
        import(
            "@std/cli/unstable-prompt-multiple-select"
        ),
    "@std/cli/unstable-prompt-select": () =>
        import(
            "@std/cli/unstable-prompt-select"
        ),
    "@std/cli/unstable-spinner": () =>
        import(
            "@std/cli/unstable-spinner"
        ),
    "@std/cli/unstable-static-line": () =>
        import(
            "@std/cli/unstable-static-line"
        ),
    "@std/collections": () =>
        import(
            "@std/collections"
        ),
    "@std/collections/aggregate-groups": () =>
        import(
            "@std/collections/aggregate-groups"
        ),
    "@std/collections/associate-by": () =>
        import(
            "@std/collections/associate-by"
        ),
    "@std/collections/associate-with": () =>
        import(
            "@std/collections/associate-with"
        ),
    "@std/collections/chunk": () =>
        import(
            "@std/collections/chunk"
        ),
    "@std/collections/deep-merge": () =>
        import(
            "@std/collections/deep-merge"
        ),
    "@std/collections/distinct": () =>
        import(
            "@std/collections/distinct"
        ),
    "@std/collections/distinct-by": () =>
        import(
            "@std/collections/distinct-by"
        ),
    "@std/collections/drop-last-while": () =>
        import(
            "@std/collections/drop-last-while"
        ),
    "@std/collections/drop-while": () =>
        import(
            "@std/collections/drop-while"
        ),
    "@std/collections/filter-entries": () =>
        import(
            "@std/collections/filter-entries"
        ),
    "@std/collections/filter-keys": () =>
        import(
            "@std/collections/filter-keys"
        ),
    "@std/collections/filter-values": () =>
        import(
            "@std/collections/filter-values"
        ),
    "@std/collections/find-single": () =>
        import(
            "@std/collections/find-single"
        ),
    "@std/collections/first-not-nullish-of": () =>
        import(
            "@std/collections/first-not-nullish-of"
        ),
    "@std/collections/includes-value": () =>
        import(
            "@std/collections/includes-value"
        ),
    "@std/collections/interleave": () =>
        import(
            "@std/collections/interleave"
        ),
    "@std/collections/intersect": () =>
        import(
            "@std/collections/intersect"
        ),
    "@std/collections/invert": () =>
        import(
            "@std/collections/invert"
        ),
    "@std/collections/invert-by": () =>
        import(
            "@std/collections/invert-by"
        ),
    "@std/collections/join-to-string": () =>
        import(
            "@std/collections/join-to-string"
        ),
    "@std/collections/map-entries": () =>
        import(
            "@std/collections/map-entries"
        ),
    "@std/collections/map-keys": () =>
        import(
            "@std/collections/map-keys"
        ),
    "@std/collections/map-not-nullish": () =>
        import(
            "@std/collections/map-not-nullish"
        ),
    "@std/collections/map-values": () =>
        import(
            "@std/collections/map-values"
        ),
    "@std/collections/max-by": () =>
        import(
            "@std/collections/max-by"
        ),
    "@std/collections/max-of": () =>
        import(
            "@std/collections/max-of"
        ),
    "@std/collections/max-with": () =>
        import(
            "@std/collections/max-with"
        ),
    "@std/collections/min-by": () =>
        import(
            "@std/collections/min-by"
        ),
    "@std/collections/min-of": () =>
        import(
            "@std/collections/min-of"
        ),
    "@std/collections/min-with": () =>
        import(
            "@std/collections/min-with"
        ),
    "@std/collections/omit": () =>
        import(
            "@std/collections/omit"
        ),
    "@std/collections/partition": () =>
        import(
            "@std/collections/partition"
        ),
    "@std/collections/partition-entries": () =>
        import(
            "@std/collections/partition-entries"
        ),
    "@std/collections/permutations": () =>
        import(
            "@std/collections/permutations"
        ),
    "@std/collections/pick": () =>
        import(
            "@std/collections/pick"
        ),
    "@std/collections/reduce-groups": () =>
        import(
            "@std/collections/reduce-groups"
        ),
    "@std/collections/running-reduce": () =>
        import(
            "@std/collections/running-reduce"
        ),
    "@std/collections/sample": () =>
        import(
            "@std/collections/sample"
        ),
    "@std/collections/sliding-windows": () =>
        import(
            "@std/collections/sliding-windows"
        ),
    "@std/collections/sort-by": () =>
        import(
            "@std/collections/sort-by"
        ),
    "@std/collections/sum-of": () =>
        import(
            "@std/collections/sum-of"
        ),
    "@std/collections/take-last-while": () =>
        import(
            "@std/collections/take-last-while"
        ),
    "@std/collections/take-while": () =>
        import(
            "@std/collections/take-while"
        ),
    "@std/collections/union": () =>
        import(
            "@std/collections/union"
        ),
    "@std/collections/unstable-binary-search": () =>
        import(
            "@std/collections/unstable-binary-search"
        ),
    "@std/collections/unstable-cycle": () =>
        import(
            "@std/collections/unstable-cycle"
        ),
    "@std/collections/unstable-zip": () =>
        import(
            "@std/collections/unstable-zip"
        ),
    "@std/collections/unzip": () =>
        import(
            "@std/collections/unzip"
        ),
    "@std/collections/without-all": () =>
        import(
            "@std/collections/without-all"
        ),
    "@std/collections/zip": () =>
        import(
            "@std/collections/zip"
        ),
    "@std/crypto": () =>
        import(
            "@std/crypto"
        ),
    "@std/crypto/aes-gcm": () =>
        import(
            "@std/crypto/aes-gcm"
        ),
    "@std/crypto/crypto": () =>
        import(
            "@std/crypto/crypto"
        ),
    "@std/crypto/timing-safe-equal": () =>
        import(
            "@std/crypto/timing-safe-equal"
        ),
    "@std/csv": () =>
        import(
            "@std/csv"
        ),
    "@std/csv/parse": () =>
        import(
            "@std/csv/parse"
        ),
    "@std/csv/parse-stream": () =>
        import(
            "@std/csv/parse-stream"
        ),
    "@std/csv/stringify": () =>
        import(
            "@std/csv/stringify"
        ),
    "@std/csv/stringify-stream": () =>
        import(
            "@std/csv/stringify-stream"
        ),
    "@std/csv/unstable-stringify": () =>
        import(
            "@std/csv/unstable-stringify"
        ),
    "@std/data-structures": () =>
        import(
            "@std/data-structures"
        ),
    "@std/data-structures/binary-heap": () =>
        import(
            "@std/data-structures/binary-heap"
        ),
    "@std/data-structures/binary-search-tree": () =>
        import(
            "@std/data-structures/binary-search-tree"
        ),
    "@std/data-structures/comparators": () =>
        import(
            "@std/data-structures/comparators"
        ),
    "@std/data-structures/deque": () =>
        import(
            "@std/data-structures/deque"
        ),
    "@std/data-structures/red-black-tree": () =>
        import(
            "@std/data-structures/red-black-tree"
        ),
    "@std/data-structures/unstable-2d-array": () =>
        import(
            "@std/data-structures/unstable-2d-array"
        ),
    "@std/data-structures/unstable-bidirectional-map": () =>
        import(
            "@std/data-structures/unstable-bidirectional-map"
        ),
    "@std/data-structures/unstable-binary-search-tree": () =>
        import(
            "@std/data-structures/unstable-binary-search-tree"
        ),
    "@std/data-structures/unstable-indexed-heap": () =>
        import(
            "@std/data-structures/unstable-indexed-heap"
        ),
    "@std/data-structures/unstable-multimap": () =>
        import(
            "@std/data-structures/unstable-multimap"
        ),
    "@std/data-structures/unstable-rolling-counter": () =>
        import(
            "@std/data-structures/unstable-rolling-counter"
        ),
    "@std/datetime": () =>
        import(
            "@std/datetime"
        ),
    "@std/datetime/constants": () =>
        import(
            "@std/datetime/constants"
        ),
    "@std/datetime/day-of-year": () =>
        import(
            "@std/datetime/day-of-year"
        ),
    "@std/datetime/difference": () =>
        import(
            "@std/datetime/difference"
        ),
    "@std/datetime/format": () =>
        import(
            "@std/datetime/format"
        ),
    "@std/datetime/is-leap": () =>
        import(
            "@std/datetime/is-leap"
        ),
    "@std/datetime/parse": () =>
        import(
            "@std/datetime/parse"
        ),
    "@std/datetime/week-of-year": () =>
        import(
            "@std/datetime/week-of-year"
        ),
    "@std/dotenv": () =>
        import(
            "@std/dotenv"
        ),
    "@std/dotenv/load": () =>
        import(
            "@std/dotenv/load"
        ),
    "@std/dotenv/parse": () =>
        import(
            "@std/dotenv/parse"
        ),
    "@std/dotenv/stringify": () =>
        import(
            "@std/dotenv/stringify"
        ),
    "@std/encoding": () =>
        import(
            "@std/encoding"
        ),
    "@std/encoding/ascii85": () =>
        import(
            "@std/encoding/ascii85"
        ),
    "@std/encoding/base32": () =>
        import(
            "@std/encoding/base32"
        ),
    "@std/encoding/base58": () =>
        import(
            "@std/encoding/base58"
        ),
    "@std/encoding/base64": () =>
        import(
            "@std/encoding/base64"
        ),
    "@std/encoding/base64url": () =>
        import(
            "@std/encoding/base64url"
        ),
    "@std/encoding/hex": () =>
        import(
            "@std/encoding/hex"
        ),
    "@std/encoding/unstable-base32": () =>
        import(
            "@std/encoding/unstable-base32"
        ),
    "@std/encoding/unstable-base32-stream": () =>
        import(
            "@std/encoding/unstable-base32-stream"
        ),
    "@std/encoding/unstable-base64": () =>
        import(
            "@std/encoding/unstable-base64"
        ),
    "@std/encoding/unstable-base64-stream": () =>
        import(
            "@std/encoding/unstable-base64-stream"
        ),
    "@std/encoding/unstable-hex": () =>
        import(
            "@std/encoding/unstable-hex"
        ),
    "@std/encoding/unstable-hex-stream": () =>
        import(
            "@std/encoding/unstable-hex-stream"
        ),
    "@std/encoding/varint": () =>
        import(
            "@std/encoding/varint"
        ),
    "@std/expect": () =>
        import(
            "@std/expect"
        ),
    "@std/expect/expect": () =>
        import(
            "@std/expect/expect"
        ),
    "@std/expect/fn": () =>
        import(
            "@std/expect/fn"
        ),
    "@std/fmt/bytes": () =>
        import(
            "@std/fmt/bytes"
        ),
    "@std/fmt/colors": () =>
        import(
            "@std/fmt/colors"
        ),
    "@std/fmt/duration": () =>
        import(
            "@std/fmt/duration"
        ),
    "@std/fmt/printf": () =>
        import(
            "@std/fmt/printf"
        ),
    "@std/front-matter": () =>
        import(
            "@std/front-matter"
        ),
    "@std/front-matter/any": () =>
        import(
            "@std/front-matter/any"
        ),
    "@std/front-matter/json": () =>
        import(
            "@std/front-matter/json"
        ),
    "@std/front-matter/test": () =>
        import(
            "@std/front-matter/test"
        ),
    "@std/front-matter/toml": () =>
        import(
            "@std/front-matter/toml"
        ),
    "@std/front-matter/types": () =>
        import(
            "@std/front-matter/types"
        ),
    "@std/front-matter/unstable-yaml": () =>
        import(
            "@std/front-matter/unstable-yaml"
        ),
    "@std/front-matter/yaml": () =>
        import(
            "@std/front-matter/yaml"
        ),
    "@std/fs": () =>
        import(
            "@std/fs"
        ),
    "@std/fs/copy": () =>
        import(
            "@std/fs/copy"
        ),
    "@std/fs/empty-dir": () =>
        import(
            "@std/fs/empty-dir"
        ),
    "@std/fs/ensure-dir": () =>
        import(
            "@std/fs/ensure-dir"
        ),
    "@std/fs/ensure-file": () =>
        import(
            "@std/fs/ensure-file"
        ),
    "@std/fs/ensure-link": () =>
        import(
            "@std/fs/ensure-link"
        ),
    "@std/fs/ensure-symlink": () =>
        import(
            "@std/fs/ensure-symlink"
        ),
    "@std/fs/eol": () =>
        import(
            "@std/fs/eol"
        ),
    "@std/fs/exists": () =>
        import(
            "@std/fs/exists"
        ),
    "@std/fs/expand-glob": () =>
        import(
            "@std/fs/expand-glob"
        ),
    "@std/fs/move": () =>
        import(
            "@std/fs/move"
        ),
    "@std/fs/unstable-chmod": () =>
        import(
            "@std/fs/unstable-chmod"
        ),
    "@std/fs/unstable-chown": () =>
        import(
            "@std/fs/unstable-chown"
        ),
    "@std/fs/unstable-copy-file": () =>
        import(
            "@std/fs/unstable-copy-file"
        ),
    "@std/fs/unstable-create": () =>
        import(
            "@std/fs/unstable-create"
        ),
    "@std/fs/unstable-link": () =>
        import(
            "@std/fs/unstable-link"
        ),
    "@std/fs/unstable-lstat": () =>
        import(
            "@std/fs/unstable-lstat"
        ),
    "@std/fs/unstable-make-temp-dir": () =>
        import(
            "@std/fs/unstable-make-temp-dir"
        ),
    "@std/fs/unstable-make-temp-file": () =>
        import(
            "@std/fs/unstable-make-temp-file"
        ),
    "@std/fs/unstable-mkdir": () =>
        import(
            "@std/fs/unstable-mkdir"
        ),
    "@std/fs/unstable-open": () =>
        import(
            "@std/fs/unstable-open"
        ),
    "@std/fs/unstable-read-dir": () =>
        import(
            "@std/fs/unstable-read-dir"
        ),
    "@std/fs/unstable-read-file": () =>
        import(
            "@std/fs/unstable-read-file"
        ),
    "@std/fs/unstable-read-link": () =>
        import(
            "@std/fs/unstable-read-link"
        ),
    "@std/fs/unstable-read-text-file": () =>
        import(
            "@std/fs/unstable-read-text-file"
        ),
    "@std/fs/unstable-real-path": () =>
        import(
            "@std/fs/unstable-real-path"
        ),
    "@std/fs/unstable-remove": () =>
        import(
            "@std/fs/unstable-remove"
        ),
    "@std/fs/unstable-rename": () =>
        import(
            "@std/fs/unstable-rename"
        ),
    "@std/fs/unstable-stat": () =>
        import(
            "@std/fs/unstable-stat"
        ),
    "@std/fs/unstable-symlink": () =>
        import(
            "@std/fs/unstable-symlink"
        ),
    "@std/fs/unstable-truncate": () =>
        import(
            "@std/fs/unstable-truncate"
        ),
    "@std/fs/unstable-types": () =>
        import(
            "@std/fs/unstable-types"
        ),
    "@std/fs/unstable-umask": () =>
        import(
            "@std/fs/unstable-umask"
        ),
    "@std/fs/unstable-utime": () =>
        import(
            "@std/fs/unstable-utime"
        ),
    "@std/fs/unstable-write-file": () =>
        import(
            "@std/fs/unstable-write-file"
        ),
    "@std/fs/unstable-write-text-file": () =>
        import(
            "@std/fs/unstable-write-text-file"
        ),
    "@std/fs/walk": () =>
        import(
            "@std/fs/walk"
        ),
    "@std/html": () =>
        import(
            "@std/html"
        ),
    "@std/html/entities": () =>
        import(
            "@std/html/entities"
        ),
    "@std/html/named-entity-list.json": () =>
        import(
            "@std/html/named-entity-list.json"
        ),
    "@std/html/unstable-escape-css": () =>
        import(
            "@std/html/unstable-escape-css"
        ),
    "@std/html/unstable-escape-js": () =>
        import(
            "@std/html/unstable-escape-js"
        ),
    "@std/html/unstable-html": () =>
        import(
            "@std/html/unstable-html"
        ),
    "@std/html/unstable-is-valid-custom-element-name": () =>
        import(
            "@std/html/unstable-is-valid-custom-element-name"
        ),
    "@std/ini": () =>
        import(
            "@std/ini"
        ),
    "@std/ini/ini-map": () =>
        import(
            "@std/ini/ini-map"
        ),
    "@std/ini/parse": () =>
        import(
            "@std/ini/parse"
        ),
    "@std/ini/stringify": () =>
        import(
            "@std/ini/stringify"
        ),
    "@std/io": () =>
        import(
            "@std/io"
        ),
    "@std/io/buffer": () =>
        import(
            "@std/io/buffer"
        ),
    "@std/io/copy": () =>
        import(
            "@std/io/copy"
        ),
    "@std/io/iterate-reader": () =>
        import(
            "@std/io/iterate-reader"
        ),
    "@std/io/read-all": () =>
        import(
            "@std/io/read-all"
        ),
    "@std/io/reader-from-stream-reader": () =>
        import(
            "@std/io/reader-from-stream-reader"
        ),
    "@std/io/to-readable-stream": () =>
        import(
            "@std/io/to-readable-stream"
        ),
    "@std/io/to-writable-stream": () =>
        import(
            "@std/io/to-writable-stream"
        ),
    "@std/io/types": () =>
        import(
            "@std/io/types"
        ),
    "@std/io/write-all": () =>
        import(
            "@std/io/write-all"
        ),
    "@std/json": () =>
        import(
            "@std/json"
        ),
    "@std/json/canonicalize": () =>
        import(
            "@std/json/canonicalize"
        ),
    "@std/json/concatenated-json-parse-stream": () =>
        import(
            "@std/json/concatenated-json-parse-stream"
        ),
    "@std/json/parse-stream": () =>
        import(
            "@std/json/parse-stream"
        ),
    "@std/json/stringify-stream": () =>
        import(
            "@std/json/stringify-stream"
        ),
    "@std/json/types": () =>
        import(
            "@std/json/types"
        ),
    "@std/jsonc": () =>
        import(
            "@std/jsonc"
        ),
    "@std/jsonc/parse": () =>
        import(
            "@std/jsonc/parse"
        ),
    "@std/log": () =>
        import(
            "@std/log"
        ),
    "@std/log/base-handler": () =>
        import(
            "@std/log/base-handler"
        ),
    "@std/log/console-handler": () =>
        import(
            "@std/log/console-handler"
        ),
    "@std/log/critical": () =>
        import(
            "@std/log/critical"
        ),
    "@std/log/debug": () =>
        import(
            "@std/log/debug"
        ),
    "@std/log/error": () =>
        import(
            "@std/log/error"
        ),
    "@std/log/file-handler": () =>
        import(
            "@std/log/file-handler"
        ),
    "@std/log/formatters": () =>
        import(
            "@std/log/formatters"
        ),
    "@std/log/get-logger": () =>
        import(
            "@std/log/get-logger"
        ),
    "@std/log/info": () =>
        import(
            "@std/log/info"
        ),
    "@std/log/levels": () =>
        import(
            "@std/log/levels"
        ),
    "@std/log/logger": () =>
        import(
            "@std/log/logger"
        ),
    "@std/log/rotating-file-handler": () =>
        import(
            "@std/log/rotating-file-handler"
        ),
    "@std/log/setup": () =>
        import(
            "@std/log/setup"
        ),
    "@std/log/warn": () =>
        import(
            "@std/log/warn"
        ),
    "@std/math": () =>
        import(
            "@std/math"
        ),
    "@std/math/clamp": () =>
        import(
            "@std/math/clamp"
        ),
    "@std/math/modulo": () =>
        import(
            "@std/math/modulo"
        ),
    "@std/math/round-to": () =>
        import(
            "@std/math/round-to"
        ),
    "@std/media-types": () =>
        import(
            "@std/media-types"
        ),
    "@std/media-types/all-extensions": () =>
        import(
            "@std/media-types/all-extensions"
        ),
    "@std/media-types/content-type": () =>
        import(
            "@std/media-types/content-type"
        ),
    "@std/media-types/extension": () =>
        import(
            "@std/media-types/extension"
        ),
    "@std/media-types/format-media-type": () =>
        import(
            "@std/media-types/format-media-type"
        ),
    "@std/media-types/get-charset": () =>
        import(
            "@std/media-types/get-charset"
        ),
    "@std/media-types/parse-media-type": () =>
        import(
            "@std/media-types/parse-media-type"
        ),
    "@std/media-types/type-by-extension": () =>
        import(
            "@std/media-types/type-by-extension"
        ),
    "@std/msgpack": () =>
        import(
            "@std/msgpack"
        ),
    "@std/msgpack/decode": () =>
        import(
            "@std/msgpack/decode"
        ),
    "@std/msgpack/encode": () =>
        import(
            "@std/msgpack/encode"
        ),
    "@std/path": () =>
        import(
            "@std/path"
        ),
    "@std/path/basename": () =>
        import(
            "@std/path/basename"
        ),
    "@std/path/common": () =>
        import(
            "@std/path/common"
        ),
    "@std/path/constants": () =>
        import(
            "@std/path/constants"
        ),
    "@std/path/dirname": () =>
        import(
            "@std/path/dirname"
        ),
    "@std/path/extname": () =>
        import(
            "@std/path/extname"
        ),
    "@std/path/format": () =>
        import(
            "@std/path/format"
        ),
    "@std/path/from-file-url": () =>
        import(
            "@std/path/from-file-url"
        ),
    "@std/path/glob-to-regexp": () =>
        import(
            "@std/path/glob-to-regexp"
        ),
    "@std/path/is-absolute": () =>
        import(
            "@std/path/is-absolute"
        ),
    "@std/path/is-glob": () =>
        import(
            "@std/path/is-glob"
        ),
    "@std/path/join": () =>
        import(
            "@std/path/join"
        ),
    "@std/path/join-globs": () =>
        import(
            "@std/path/join-globs"
        ),
    "@std/path/normalize": () =>
        import(
            "@std/path/normalize"
        ),
    "@std/path/normalize-glob": () =>
        import(
            "@std/path/normalize-glob"
        ),
    "@std/path/parse": () =>
        import(
            "@std/path/parse"
        ),
    "@std/path/posix": () =>
        import(
            "@std/path/posix"
        ),
    "@std/path/posix/basename": () =>
        import(
            "@std/path/posix/basename"
        ),
    "@std/path/posix/common": () =>
        import(
            "@std/path/posix/common"
        ),
    "@std/path/posix/constants": () =>
        import(
            "@std/path/posix/constants"
        ),
    "@std/path/posix/dirname": () =>
        import(
            "@std/path/posix/dirname"
        ),
    "@std/path/posix/extname": () =>
        import(
            "@std/path/posix/extname"
        ),
    "@std/path/posix/format": () =>
        import(
            "@std/path/posix/format"
        ),
    "@std/path/posix/from-file-url": () =>
        import(
            "@std/path/posix/from-file-url"
        ),
    "@std/path/posix/glob-to-regexp": () =>
        import(
            "@std/path/posix/glob-to-regexp"
        ),
    "@std/path/posix/is-absolute": () =>
        import(
            "@std/path/posix/is-absolute"
        ),
    "@std/path/posix/is-glob": () =>
        import(
            "@std/path/posix/is-glob"
        ),
    "@std/path/posix/join": () =>
        import(
            "@std/path/posix/join"
        ),
    "@std/path/posix/join-globs": () =>
        import(
            "@std/path/posix/join-globs"
        ),
    "@std/path/posix/normalize": () =>
        import(
            "@std/path/posix/normalize"
        ),
    "@std/path/posix/normalize-glob": () =>
        import(
            "@std/path/posix/normalize-glob"
        ),
    "@std/path/posix/parse": () =>
        import(
            "@std/path/posix/parse"
        ),
    "@std/path/posix/relative": () =>
        import(
            "@std/path/posix/relative"
        ),
    "@std/path/posix/resolve": () =>
        import(
            "@std/path/posix/resolve"
        ),
    "@std/path/posix/to-file-url": () =>
        import(
            "@std/path/posix/to-file-url"
        ),
    "@std/path/posix/to-namespaced-path": () =>
        import(
            "@std/path/posix/to-namespaced-path"
        ),
    "@std/path/relative": () =>
        import(
            "@std/path/relative"
        ),
    "@std/path/resolve": () =>
        import(
            "@std/path/resolve"
        ),
    "@std/path/to-file-url": () =>
        import(
            "@std/path/to-file-url"
        ),
    "@std/path/to-namespaced-path": () =>
        import(
            "@std/path/to-namespaced-path"
        ),
    "@std/path/types": () =>
        import(
            "@std/path/types"
        ),
    "@std/path/windows": () =>
        import(
            "@std/path/windows"
        ),
    "@std/path/windows/basename": () =>
        import(
            "@std/path/windows/basename"
        ),
    "@std/path/windows/common": () =>
        import(
            "@std/path/windows/common"
        ),
    "@std/path/windows/constants": () =>
        import(
            "@std/path/windows/constants"
        ),
    "@std/path/windows/dirname": () =>
        import(
            "@std/path/windows/dirname"
        ),
    "@std/path/windows/extname": () =>
        import(
            "@std/path/windows/extname"
        ),
    "@std/path/windows/format": () =>
        import(
            "@std/path/windows/format"
        ),
    "@std/path/windows/from-file-url": () =>
        import(
            "@std/path/windows/from-file-url"
        ),
    "@std/path/windows/glob-to-regexp": () =>
        import(
            "@std/path/windows/glob-to-regexp"
        ),
    "@std/path/windows/is-absolute": () =>
        import(
            "@std/path/windows/is-absolute"
        ),
    "@std/path/windows/is-glob": () =>
        import(
            "@std/path/windows/is-glob"
        ),
    "@std/path/windows/join": () =>
        import(
            "@std/path/windows/join"
        ),
    "@std/path/windows/join-globs": () =>
        import(
            "@std/path/windows/join-globs"
        ),
    "@std/path/windows/normalize": () =>
        import(
            "@std/path/windows/normalize"
        ),
    "@std/path/windows/normalize-glob": () =>
        import(
            "@std/path/windows/normalize-glob"
        ),
    "@std/path/windows/parse": () =>
        import(
            "@std/path/windows/parse"
        ),
    "@std/path/windows/relative": () =>
        import(
            "@std/path/windows/relative"
        ),
    "@std/path/windows/resolve": () =>
        import(
            "@std/path/windows/resolve"
        ),
    "@std/path/windows/to-file-url": () =>
        import(
            "@std/path/windows/to-file-url"
        ),
    "@std/path/windows/to-namespaced-path": () =>
        import(
            "@std/path/windows/to-namespaced-path"
        ),
    "@std/random": () =>
        import(
            "@std/random"
        ),
    "@std/random/between": () =>
        import(
            "@std/random/between"
        ),
    "@std/random/get-random-values-seeded": () =>
        import(
            "@std/random/get-random-values-seeded"
        ),
    "@std/random/integer-between": () =>
        import(
            "@std/random/integer-between"
        ),
    "@std/random/next-float-64": () =>
        import(
            "@std/random/next-float-64"
        ),
    "@std/random/sample": () =>
        import(
            "@std/random/sample"
        ),
    "@std/random/seeded": () =>
        import(
            "@std/random/seeded"
        ),
    "@std/random/shuffle": () =>
        import(
            "@std/random/shuffle"
        ),
    "@std/regexp": () =>
        import(
            "@std/regexp"
        ),
    "@std/regexp/escape": () =>
        import(
            "@std/regexp/escape"
        ),
    "@std/regexp/unstable-replace-all-async": () =>
        import(
            "@std/regexp/unstable-replace-all-async"
        ),
    "@std/semver": () =>
        import(
            "@std/semver"
        ),
    "@std/semver/can-parse": () =>
        import(
            "@std/semver/can-parse"
        ),
    "@std/semver/compare": () =>
        import(
            "@std/semver/compare"
        ),
    "@std/semver/difference": () =>
        import(
            "@std/semver/difference"
        ),
    "@std/semver/equals": () =>
        import(
            "@std/semver/equals"
        ),
    "@std/semver/format": () =>
        import(
            "@std/semver/format"
        ),
    "@std/semver/format-range": () =>
        import(
            "@std/semver/format-range"
        ),
    "@std/semver/greater-or-equal": () =>
        import(
            "@std/semver/greater-or-equal"
        ),
    "@std/semver/greater-than": () =>
        import(
            "@std/semver/greater-than"
        ),
    "@std/semver/greater-than-range": () =>
        import(
            "@std/semver/greater-than-range"
        ),
    "@std/semver/increment": () =>
        import(
            "@std/semver/increment"
        ),
    "@std/semver/is-range": () =>
        import(
            "@std/semver/is-range"
        ),
    "@std/semver/is-semver": () =>
        import(
            "@std/semver/is-semver"
        ),
    "@std/semver/less-or-equal": () =>
        import(
            "@std/semver/less-or-equal"
        ),
    "@std/semver/less-than": () =>
        import(
            "@std/semver/less-than"
        ),
    "@std/semver/less-than-range": () =>
        import(
            "@std/semver/less-than-range"
        ),
    "@std/semver/max-satisfying": () =>
        import(
            "@std/semver/max-satisfying"
        ),
    "@std/semver/min-satisfying": () =>
        import(
            "@std/semver/min-satisfying"
        ),
    "@std/semver/not-equals": () =>
        import(
            "@std/semver/not-equals"
        ),
    "@std/semver/parse": () =>
        import(
            "@std/semver/parse"
        ),
    "@std/semver/parse-range": () =>
        import(
            "@std/semver/parse-range"
        ),
    "@std/semver/range-intersects": () =>
        import(
            "@std/semver/range-intersects"
        ),
    "@std/semver/satisfies": () =>
        import(
            "@std/semver/satisfies"
        ),
    "@std/semver/try-parse": () =>
        import(
            "@std/semver/try-parse"
        ),
    "@std/semver/try-parse-range": () =>
        import(
            "@std/semver/try-parse-range"
        ),
    "@std/semver/types": () =>
        import(
            "@std/semver/types"
        ),
    "@std/streams": () =>
        import(
            "@std/streams"
        ),
    "@std/streams/buffer": () =>
        import(
            "@std/streams/buffer"
        ),
    "@std/streams/byte-slice-stream": () =>
        import(
            "@std/streams/byte-slice-stream"
        ),
    "@std/streams/concat-readable-streams": () =>
        import(
            "@std/streams/concat-readable-streams"
        ),
    "@std/streams/delimiter-stream": () =>
        import(
            "@std/streams/delimiter-stream"
        ),
    "@std/streams/early-zip-readable-streams": () =>
        import(
            "@std/streams/early-zip-readable-streams"
        ),
    "@std/streams/limited-bytes-transform-stream": () =>
        import(
            "@std/streams/limited-bytes-transform-stream"
        ),
    "@std/streams/limited-transform-stream": () =>
        import(
            "@std/streams/limited-transform-stream"
        ),
    "@std/streams/merge-readable-streams": () =>
        import(
            "@std/streams/merge-readable-streams"
        ),
    "@std/streams/text-delimiter-stream": () =>
        import(
            "@std/streams/text-delimiter-stream"
        ),
    "@std/streams/text-line-stream": () =>
        import(
            "@std/streams/text-line-stream"
        ),
    "@std/streams/to-array-buffer": () =>
        import(
            "@std/streams/to-array-buffer"
        ),
    "@std/streams/to-blob": () =>
        import(
            "@std/streams/to-blob"
        ),
    "@std/streams/to-bytes": () =>
        import(
            "@std/streams/to-bytes"
        ),
    "@std/streams/to-json": () =>
        import(
            "@std/streams/to-json"
        ),
    "@std/streams/to-text": () =>
        import(
            "@std/streams/to-text"
        ),
    "@std/streams/to-transform-stream": () =>
        import(
            "@std/streams/to-transform-stream"
        ),
    "@std/streams/unstable-abort-stream": () =>
        import(
            "@std/streams/unstable-abort-stream"
        ),
    "@std/streams/unstable-batch-stream": () =>
        import(
            "@std/streams/unstable-batch-stream"
        ),
    "@std/streams/unstable-capped-delimiter-stream": () =>
        import(
            "@std/streams/unstable-capped-delimiter-stream"
        ),
    "@std/streams/unstable-fixed-chunk-stream": () =>
        import(
            "@std/streams/unstable-fixed-chunk-stream"
        ),
    "@std/streams/unstable-to-byte-stream": () =>
        import(
            "@std/streams/unstable-to-byte-stream"
        ),
    "@std/streams/unstable-to-lines": () =>
        import(
            "@std/streams/unstable-to-lines"
        ),
    "@std/streams/zip-readable-streams": () =>
        import(
            "@std/streams/zip-readable-streams"
        ),
    "@std/tar": () =>
        import(
            "@std/tar"
        ),
    "@std/tar/tar-stream": () =>
        import(
            "@std/tar/tar-stream"
        ),
    "@std/tar/untar-stream": () =>
        import(
            "@std/tar/untar-stream"
        ),
    "@std/testing/bdd": () =>
        import(
            "@std/testing/bdd"
        ),
    "@std/testing/mock": () =>
        import(
            "@std/testing/mock"
        ),
    "@std/testing/snapshot": () =>
        import(
            "@std/testing/snapshot"
        ),
    "@std/testing/time": () =>
        import(
            "@std/testing/time"
        ),
    "@std/testing/types": () =>
        import(
            "@std/testing/types"
        ),
    "@std/testing/unstable-bdd": () =>
        import(
            "@std/testing/unstable-bdd"
        ),
    "@std/testing/unstable-snapshot": () =>
        import(
            "@std/testing/unstable-snapshot"
        ),
    "@std/testing/unstable-stub": () =>
        import(
            "@std/testing/unstable-stub"
        ),
    "@std/testing/unstable-stub-property": () =>
        import(
            "@std/testing/unstable-stub-property"
        ),
    "@std/testing/unstable-types": () =>
        import(
            "@std/testing/unstable-types"
        ),
    "@std/text": () =>
        import(
            "@std/text"
        ),
    "@std/text/closest-string": () =>
        import(
            "@std/text/closest-string"
        ),
    "@std/text/compare-similarity": () =>
        import(
            "@std/text/compare-similarity"
        ),
    "@std/text/levenshtein-distance": () =>
        import(
            "@std/text/levenshtein-distance"
        ),
    "@std/text/to-camel-case": () =>
        import(
            "@std/text/to-camel-case"
        ),
    "@std/text/to-kebab-case": () =>
        import(
            "@std/text/to-kebab-case"
        ),
    "@std/text/to-pascal-case": () =>
        import(
            "@std/text/to-pascal-case"
        ),
    "@std/text/to-snake-case": () =>
        import(
            "@std/text/to-snake-case"
        ),
    "@std/text/unstable-dedent": () =>
        import(
            "@std/text/unstable-dedent"
        ),
    "@std/text/unstable-longest-common-prefix": () =>
        import(
            "@std/text/unstable-longest-common-prefix"
        ),
    "@std/text/unstable-reverse": () =>
        import(
            "@std/text/unstable-reverse"
        ),
    "@std/text/unstable-slugify": () =>
        import(
            "@std/text/unstable-slugify"
        ),
    "@std/text/unstable-to-constant-case": () =>
        import(
            "@std/text/unstable-to-constant-case"
        ),
    "@std/text/unstable-to-sentence-case": () =>
        import(
            "@std/text/unstable-to-sentence-case"
        ),
    "@std/text/unstable-to-title-case": () =>
        import(
            "@std/text/unstable-to-title-case"
        ),
    "@std/text/unstable-trim-by": () =>
        import(
            "@std/text/unstable-trim-by"
        ),
    "@std/text/unstable-truncate": () =>
        import(
            "@std/text/unstable-truncate"
        ),
    "@std/text/word-similarity-sort": () =>
        import(
            "@std/text/word-similarity-sort"
        ),
    "@std/toml": () =>
        import(
            "@std/toml"
        ),
    "@std/toml/parse": () =>
        import(
            "@std/toml/parse"
        ),
    "@std/toml/stringify": () =>
        import(
            "@std/toml/stringify"
        ),
    "@std/ulid": () =>
        import(
            "@std/ulid"
        ),
    "@std/ulid/decode-time": () =>
        import(
            "@std/ulid/decode-time"
        ),
    "@std/ulid/monotonic-ulid": () =>
        import(
            "@std/ulid/monotonic-ulid"
        ),
    "@std/ulid/ulid": () =>
        import(
            "@std/ulid/ulid"
        ),
    "@std/uuid": () =>
        import(
            "@std/uuid"
        ),
    "@std/uuid/common": () =>
        import(
            "@std/uuid/common"
        ),
    "@std/uuid/constants": () =>
        import(
            "@std/uuid/constants"
        ),
    "@std/uuid/unstable-v6": () =>
        import(
            "@std/uuid/unstable-v6"
        ),
    "@std/uuid/v1": () =>
        import(
            "@std/uuid/v1"
        ),
    "@std/uuid/v3": () =>
        import(
            "@std/uuid/v3"
        ),
    "@std/uuid/v4": () =>
        import(
            "@std/uuid/v4"
        ),
    "@std/uuid/v5": () =>
        import(
            "@std/uuid/v5"
        ),
    "@std/uuid/v7": () =>
        import(
            "@std/uuid/v7"
        ),
    "@std/xml": () =>
        import(
            "@std/xml"
        ),
    "@std/xml/parse": () =>
        import(
            "@std/xml/parse"
        ),
    "@std/xml/parse-records": () =>
        import(
            "@std/xml/parse-records"
        ),
    "@std/xml/parse-stream": () =>
        import(
            "@std/xml/parse-stream"
        ),
    "@std/xml/stringify": () =>
        import(
            "@std/xml/stringify"
        ),
    "@std/xml/types": () =>
        import(
            "@std/xml/types"
        ),
    "@std/yaml": () =>
        import(
            "@std/yaml"
        ),
    "@std/yaml/parse": () =>
        import(
            "@std/yaml/parse"
        ),
    "@std/yaml/stringify": () =>
        import(
            "@std/yaml/stringify"
        ),
    "@std/yaml/types": () =>
        import(
            "@std/yaml/types"
        ),
    "@std/yaml/unstable-parse": () =>
        import(
            "@std/yaml/unstable-parse"
        ),
    "@std/yaml/unstable-stringify": () =>
        import(
            "@std/yaml/unstable-stringify"
        ),
    "replicad": () =>
        import(
            "replicad"
        ),
}

/** Every specifier a CAD script may import. */
export const ALLOWED: readonly string[] = Object.keys(MODULES)
